### ISSUE TITLE
Does Renderlab works with Gymnasium Atari Environment ?

### ISSUE THREAD

**Issue by gusdelact** [ryanrudes/renderlab#3]
I tried to use ALE/AirRaid-v5 environment

This exception raised:
NamespaceNotFound: Namespace ALE not found. Have you installed the proper package for ALE?

---------------------------------------------------------------------------
NamespaceNotFound                         Traceback (most recent call last)
[<ipython-input-11-337dadad91fe>](https://localhost:8080/#) in <cell line: 1>()
----> 1 env = gym.make("ALE/AirRaid-v5", render_mode="rgb_array")
      2 env = rl.RenderFrame(env, "./output")
      3 observation, info = env.reset(seed=42)
      4 for _ in range(1000):
      5    action = env.action_space.sample()  # this is where you would insert your policy

4 frames
[/usr/local/lib/python3.10/dist-packages/gymnasium/envs/registration.py](https://localhost:8080/#) in _check_namespace_exists(ns)
    358         suggestion_msg = f"Have you installed the proper package for {ns}?"
    359 
--> 360     raise error.NamespaceNotFound(f"Namespace {ns} not found. {suggestion_msg}")
    361 
    362

**Comment by ryanrudes** [comment]
As the exception suggests, you must install the ALE package in order to use the ROM files for these Atari environments. This is done automatically if you include the `accept-rom-license` flag in your installation of `gymnasium`

```
pip install gymnasium[atari, accept-rom-licesnse]
```
